export default{
    ADD_TODO: 'ADD_TODO',
    COMPLETE_TODO: 'COMPLETE_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    REMINDER_TODO: 'REMINDER_TODO',
    DATE_CHANGE : 'DATE_CHANGE',
    EDIT_TODO : 'EDIT-TODO',
    FORM_TEXT : 'FORM_TEXT',
    NAME_CHANGE : 'NAME_CHANGE',
    SET_TODO : 'SET_TODO',
    LOADING_TODO : 'LOADING_TODO',
    ERROR_TODO : 'ERROR_TODO',
    GET_TODO : 'GET_TODO'
};